### ISSUE TITLE
MaxxFan integration

### ISSUE THREAD

**Issue by soffes** [soffes/van#9]
Apparently there is an RJ45 connector on the van and if you short some of the wires together in the right way, it can control the van. I have some transistors in the mail so I should be able to rig something up with ESPHome.

**Comment by zef** [comment]
Over the weekend I've been editing a video with some footage I took in August 2020 before I installed my fan. If I don't finish it soon I'll get you the details directly...

But basically one thing I've been trying to think through with this kind of feature is based in some limitations in that the ethernet interface is basically a duplication of the control panel buttons, and therefore it's hard to reliably implement full automation because the state of the fan may be unknown to the microcontroller, particularly if any fan control has been done manually through the buttons on the fan or the remote control that I think is included with your model.

Implementing "toggle fan direction" or "toggle open/close" or "toggle on/off state" is basically no problem, because these are just button presses. But "Open fan" requires knowledge of whether the fan is already open or not. "Turn the fan on and set the speed to 7" is also requires knowing the current on/off state and the current fan speed, and furthermore whether the "hold" feature is set — because the "hold" feature being on makes the up/down buttons control the hold temperature rather than the fan speed.

I don't know exactly what you will want to automate, but I just wanted to get you thinking about the limitations.

A few options/thoughts:

- You could implement code that is fully responsible for controlling the fan and tracks the current fan state so that it always knows what the fan state is, and therefore can always get to the state you want. The downside here is that using your remote or manual control would break the state in the controller, which might be a dealbreaker, but may also be workable depending on what you want. For this you might need custom code and `MQTT` messages, rather than ESPHome, but I'm not sure. Maybe you can do enough what you wanted with just ESPHome config.

- Maybe you don't need to know the full state. It depends on what features you want to automate. If you just want voice control for the buttons, you already know the state and you just execute the correct commands yourself. If you wanted to implement something that changes fan speed to 3, but you don't know the current fan speed, your "change fan speed" function could press down 10 times and up 3. Not the most elegant perhaps but workable?

- I'm not sure if there is a way to actually detect current state from the fan. I didn't really check out the phone jack that lives next to the ethernet jack. There may be some other methods to determine the current fan state that I don't know about.

Also I recognize that a "perfect" implementation of fan automation here might be more trouble than it's worth — just trying to let you know some thoughts that I have had when I was thinking about this for myself!

**Comment by soffes** [comment]
Super helpful! Thank you!

I may only control through HA so it can track the state. That might be annoying though. We'll see!

**Comment by soffes** [comment]
@zef do you know what the pinout of the RJ45 connector corresponds to with the fan?

**Comment by zef** [comment]
Just [posted it on my website](https://zef.studio/projects/maxxfan/), and almost done with the video — which isn't something you need, just using this as motivation to get it done! Let me know if you have any questions!

**Comment by soffes** [comment]
@zef this is perfect! Thank you!!

**Comment by soffes** [comment]
Decided against this at least for now. The connector doesn't really fit in the fan while it's in its housing :/
